[package]
name = "bump2version"
version = "0.1.6"
edition = "2024"
description = "⬆️ Easily manage version numbers in your projects."
license = "MIT"
keywords = ["cli", "semver", "versioning", "bumpversion", "release"]
categories = ["command-line-utilities", "development-tools"]
repository = "https://github.com/wiseaidev/bump2version"
documentation = "https://docs.rs/bump2version"
homepage = "https://github.com/wiseaidev/bump2version"
authors = ["Mahmoud Harmouch <oss@wiseai.dev>"]
rust-version = "1.89"
build = "build.rs"
exclude = [
    "/tests",
    ".*",
    "/python",
    "/assets",
    "/benches",
    "/benchmarks",
    "NODE.md",
    "PYTHON.md",
    "package.json",
    "package-lock.json",
    "pyproject.toml",
]

[lib]
name = "bump2version"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bump2version"
path = "src/bin/main.rs"
required-features = ["rust-binary"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
clap = { version = "4.6.6", features = ["derive", "color", "wrap_help"], optional = true }
regex = { version = "1.13.1", default-features = false, features = ["unicode"] }
gix = { version = "0.87.1", default-features = false, features = ["status", "worktree-mutation", "revision", "index", "sha1"], optional = true }
anyhow = { version = "1.0.104", default-features = false, optional = true }
smallvec = { version = "1.16.0", default-features = false }
thiserror = { version = "2.0.20", default-features = false }
indexmap = { version = "2.14.2", default-features = false }
pyo3 = { version = "0.29.2", features = ["extension-module"], optional = true }
napi = { version = "3.12.2", default-features = false, features = ["napi4"], optional = true }
napi-derive = { version = "3.6.3", optional = true }

[build-dependencies]
napi-build = { version = "2.4.1", optional = true }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
tempfile = "3.27.0"

[[bench]]
name = "benchmark"
harness = false

[features]
default = ["std"]
std = ["regex/std", "gix", "anyhow", "indexmap/std"]
cli = ["clap", "std"]
python = ["pyo3", "std"]
node = ["napi", "napi-derive", "napi-build", "std"]
rust-binary = ["cli", "std"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "thin"
strip = "symbols"
panic = "abort"

[badges]
maintenance = { status = "actively-developed" }
